@startuml
'https://plantuml.com/class-diagram

class TextPrinter {
- String sentence
+ TextPrinter(String sentence)
+ void process(WordProcessor processor)
}
interface WordProcessor {
+ String process(String s)
}

class TextPrinterWithFunction {
- String sentence
+ TextPrinter(String sentence)
+ void process(Function<String, String> processor)
}

@enduml